import { describe, expect, it } from "vitest";
import { analyzeGacha, createDefaultGachaDraft, decodeGachaDraft, encodeGachaDraft, GACHA_IMPORT_TEMPLATE, GACHA_IMPORT_TEMPLATE_FILENAME, normalizeGachaDraft, parsePrizeTable, probabilityAtLeastOnce, sanitizeSpreadsheetText } from "./gacha-planner";
describe("gacha planner", () => {
  it("calculates probability, cost and points at 1P = 1 yen", () => { expect(probabilityAtLeastOnce(.1, 10)).toBeCloseTo(.6513215599, 8); const d = normalizeGachaDraft({ ...createDefaultGachaDraft(), pointsPerDraw: 100, fixedCost: 1000, plannedDraws: 20, prizes: [{ id: "s", rarity: "S", name: "レア", probability: 2, cost: 1000, stockType: "limited", stock: 10 }, { id: "n", rarity: "N", name: "通常", probability: 98, cost: 0, stockType: "unlimited", stock: null }] }); const r = analyzeGacha(d); expect(r.totalPoints).toBe(2000); expect(r.expectedCostPerDraw).toBe(20); expect(r.breakEvenDraws).toBe(13); expect(r.expectedMargin).toBe(600); });
  it("calculates bundles first and singles for the remainder", () => { const d = normalizeGachaDraft({ ...createDefaultGachaDraft(), pointsPerDraw: 500, plannedDraws: 100, bundleEnabled: true, bundleDraws: 11, bundlePoints: 5000 }); const r = analyzeGacha(d); expect(r.bundleCount).toBe(9); expect(r.remainingSingleDraws).toBe(1); expect(r.singleTotalPoints).toBe(50000); expect(r.totalPoints).toBe(45500); expect(r.bundleSavingPoints).toBe(4500); expect(r.effectivePointsPerDraw).toBe(455); });
  it("requires 100 percent for a no-miss gacha", () => { const d = normalizeGachaDraft({ ...createDefaultGachaDraft(), mode: "normal", prizes: [{ id: "a", rarity: "S", name: "限定", probability: 80, cost: 0, stockType: "unlimited", stock: null }] }); expect(analyzeGacha(d).warnings.map(w => w.code)).toContain("probability-total"); });
  it("uses the remaining probability as a miss in dark gacha", () => { const d = normalizeGachaDraft({ ...createDefaultGachaDraft(), mode: "dark", prizes: [{ id: "a", rarity: "S", name: "限定", probability: 30, cost: 0, stockType: "unlimited", stock: null }] }); expect(analyzeGacha(d).missProbability).toBe(70); });
  it("rejects a dark gacha total over 100 percent", () => { const d = normalizeGachaDraft({ ...createDefaultGachaDraft(), mode: "dark", prizes: [{ id: "a", rarity: "S", name: "限定", probability: 60, cost: 0, stockType: "unlimited", stock: null }, { id: "b", rarity: "N", name: "通常", probability: 50, cost: 0, stockType: "unlimited", stock: null }] }); expect(analyzeGacha(d).warnings.map(w => w.code)).toContain("probability-over"); });
  it("warns only for limited stock", () => { const base = createDefaultGachaDraft(); const limited = normalizeGachaDraft({ ...base, plannedDraws: 100, prizes: [{ id: "a", rarity: "S", name: "限定", probability: 100, cost: 0, stockType: "limited", stock: 2 }] }); const unlimited = normalizeGachaDraft({ ...limited, prizes: [{ ...limited.prizes[0], stockType: "unlimited", stock: null }] }); expect(analyzeGacha(limited).warnings.map(w => w.code)).toContain("stock-shortage:a"); expect(analyzeGacha(unlimited).warnings.map(w => w.code)).not.toContain("stock-shortage:a"); });
  it("migrates the old yen field to points", () => { const old = JSON.stringify({ ...createDefaultGachaDraft(), version: 2, pointsPerDraw: undefined, revenuePerDraw: 700 }); const migrated = decodeGachaDraft(old); expect(migrated?.version).toBe(3); expect(migrated?.pointsPerDraw).toBe(700); expect(decodeGachaDraft(encodeGachaDraft(createDefaultGachaDraft()))).toEqual(createDefaultGachaDraft()); });
  it("clamps values, imports tables and neutralizes formulas", () => { const d = createDefaultGachaDraft(); expect(normalizeGachaDraft({ ...d, plannedDraws: 999999, pointsPerDraw: -1 }).plannedDraws).toBe(10000); const rows = parsePrizeTable("レア,景品,確率,原価,在庫\nS,特賞,2,1000,2\nN,参加賞,98,0,"); expect(rows[0].stockType).toBe("limited"); expect(rows[1].stockType).toBe("unlimited"); expect(sanitizeSpreadsheetText("=HYPERLINK(...)" )).toBe("'=HYPERLINK(...)"); });
  it("provides an Excel-friendly CSV template and accepts tab-separated tables", () => { expect(GACHA_IMPORT_TEMPLATE_FILENAME).toBe("ガチャ景品読み込みテンプレート.csv"); expect(GACHA_IMPORT_TEMPLATE).toContain("レアリティ,景品名,確率,原価,在庫\r\n"); const templateRows = parsePrizeTable(GACHA_IMPORT_TEMPLATE); expect(templateRows).toHaveLength(2); expect(templateRows[1].stockType).toBe("unlimited"); const tabRows = parsePrizeTable("レアリティ\t景品名\t確率\t原価\t在庫\nS\t特賞\t100\t0\t"); expect(tabRows).toHaveLength(1); expect(tabRows[0]).toMatchObject({ rarity: "S", name: "特賞", probability: 100, stockType: "unlimited" }); });
});
