"use client";

import { useEffect, useMemo, useState } from "react";
import { analyzeGacha, createDefaultGachaDraft, decodeGachaDraft, encodeGachaDraft, formatPercent, formatPoints, formatYen, GACHA_STORAGE_KEY, GachaDraft, GachaPrize, MAX_GACHA_PRIZES, parsePrizeTable } from "@/lib/gacha-planner";

const modeLabels = { normal: "通常（はずれなし）", dark: "闇ガチャ（はずれあり）" } as const;
const numeric = (value: string) => Number.isFinite(Number(value)) ? Number(value) : 0;

function downloadPng(draft: GachaDraft) {
  const result = analyzeGacha(draft); const canvas = document.createElement("canvas"); canvas.width = 1080; canvas.height = 1350; const ctx = canvas.getContext("2d"); if (!ctx) return;
  ctx.fillStyle = "#fff9fb"; ctx.fillRect(0, 0, 1080, 1350); ctx.fillStyle = "#f8d7e2"; ctx.fillRect(0, 0, 1080, 190); ctx.fillStyle = "#302934"; ctx.font = "900 52px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(draft.projectName, 70, 92); ctx.font = "700 25px sans-serif"; ctx.fillText(`ガチャ設定シート${draft.hostName ? ` ／ ${draft.hostName}` : ""}`, 72, 142);
  const metrics = [["排出率合計", `${result.probabilityTotal.toFixed(2)}%`], ["期待原価／回", formatYen(result.expectedCostPerDraw)], ["想定獲得ポイント", formatPoints(result.totalPoints)], ["収支見込み", formatYen(result.expectedMargin)]]; metrics.forEach(([label, value], i) => { const x = 70 + (i % 2) * 480, y = 235 + Math.floor(i / 2) * 140; ctx.fillStyle = "#ffffff"; ctx.fillRect(x, y, 430, 105); ctx.fillStyle = "#735d68"; ctx.font = "600 22px sans-serif"; ctx.fillText(label, x + 25, y + 35); ctx.fillStyle = "#302934"; ctx.font = "900 34px sans-serif"; ctx.fillText(value, x + 25, y + 78); });
  ctx.fillStyle = "#302934"; ctx.font = "900 30px sans-serif"; ctx.fillText(`景品設定　${modeLabels[draft.mode]}・ガチャ${draft.plannedDraws}回想定`, 70, 535); ctx.font = "700 20px sans-serif"; ctx.fillStyle = "#735d68"; ctx.fillText("レア　景品名　　　　　　　　　　　　　確率　　 原価　　 在庫", 72, 580);
  draft.prizes.slice(0, 11).forEach((p, i) => { const y = 622 + i * 48; ctx.fillStyle = i % 2 ? "#fff" : "#f8eef2"; ctx.fillRect(65, y - 32, 950, 43); ctx.fillStyle = "#302934"; ctx.font = "600 20px sans-serif"; const name = p.name.length > 19 ? `${p.name.slice(0, 18)}…` : p.name; ctx.fillText(p.rarity, 78, y); ctx.fillText(name, 155, y); ctx.fillText(`${p.probability}%`, 665, y); ctx.fillText(formatYen(p.cost), 780, y); ctx.fillText(p.stockType === "unlimited" ? "制限なし" : `${p.stock}個`, 920, y); });
  if (draft.prizes.length > 11) { ctx.fillStyle = "#735d68"; ctx.fillText(`ほか ${draft.prizes.length - 11} 件`, 75, 1160); }
  const firstWarning = result.warnings[0]; ctx.fillStyle = firstWarning.severity === "error" ? "#b54758" : "#665444"; ctx.font = "700 21px sans-serif"; const warning = firstWarning.message.length > 47 ? `${firstWarning.message.slice(0, 46)}…` : firstWarning.message; ctx.fillText(`確認: ${warning}`, 70, 1210); ctx.fillStyle = "#735d68"; ctx.font = "500 17px sans-serif"; ctx.fillText("収支は1P＝1円換算の参考値です。実際の受取額や利益を保証するものではありません。", 70, 1260); ctx.fillText(`すしうさどっとねっと｜作成 ${new Date().toLocaleString("ja-JP")}`, 70, 1305);
  const link = document.createElement("a"); link.download = "gacha-plan.png"; link.href = canvas.toDataURL("image/png"); link.click();
}

function drawWrappedText(ctx: CanvasRenderingContext2D, value: string, x: number, y: number, maxWidth: number, lineHeight: number, maxLines: number) {
  const characters = [...value]; let line = "", lines = 0;
  for (const character of characters) { const next = line + character; if (ctx.measureText(next).width > maxWidth && line) { ctx.fillText(line, x, y + lines * lineHeight); lines += 1; line = character; if (lines >= maxLines) return; } else line = next; }
  if (line && lines < maxLines) ctx.fillText(line, x, y + lines * lineHeight);
}

function downloadListenerPng(draft: GachaDraft) {
  const result = analyzeGacha(draft); const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 675; const ctx = canvas.getContext("2d"); if (!ctx) return;
  const gradient = ctx.createLinearGradient(0, 0, 1200, 675); gradient.addColorStop(0, "#fff8fb"); gradient.addColorStop(1, "#f7e9f0"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, 1200, 675);
  ctx.fillStyle = "#f4cada"; ctx.fillRect(0, 0, 1200, 166); ctx.fillStyle = "#302934"; ctx.font = "900 46px 'Noto Sans JP Caption', sans-serif"; drawWrappedText(ctx, draft.projectName, 40, 60, 720, 50, 2); ctx.fillStyle = "#6d5963"; ctx.font = "700 21px 'Noto Sans JP Caption', sans-serif"; if (draft.hostName) ctx.fillText(draft.hostName, 42, 146);
  ctx.fillStyle = "#ffffff"; ctx.fillRect(805, 25, 355, 116); ctx.fillStyle = "#a84f70"; ctx.font = "900 37px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(`1回 ${formatPoints(draft.pointsPerDraw)}`, 830, 78); if (draft.bundleEnabled) { ctx.fillStyle = "#51434a"; ctx.font = "800 24px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(`${draft.bundleDraws}連 ${formatPoints(draft.bundlePoints)}`, 832, 118); }
  ctx.fillStyle = draft.mode === "normal" ? "#3f7a61" : "#9f4559"; ctx.fillRect(40, 181, 206, 43); ctx.fillStyle = "#ffffff"; ctx.font = "800 21px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(draft.mode === "normal" ? "はずれなし" : `はずれ ${result.missProbability.toFixed(2)}%`, 58, 211); ctx.fillStyle = "#302934"; ctx.font = "900 28px 'Noto Sans JP Caption', sans-serif"; ctx.fillText("景品ラインナップ", 270, 212);
  const displayedPrizes = draft.prizes.slice(0, 12); const twoColumns = displayedPrizes.length > 6; displayedPrizes.forEach((prize, index) => { const column = twoColumns ? Math.floor(index / 6) : 0; const row = twoColumns ? index % 6 : index; const x = 40 + column * 580; const y = 240 + row * 54; const rowWidth = twoColumns ? 540 : 1120; ctx.fillStyle = row % 2 ? "#ffffff" : "#faedf2"; ctx.fillRect(x, y, rowWidth, 46); ctx.fillStyle = "#a84f70"; ctx.fillRect(x + 10, y + 7, 66, 32); ctx.fillStyle = "#ffffff"; ctx.font = "900 19px 'Noto Sans JP Caption', sans-serif"; const rarity = prize.rarity.length > 4 ? `${prize.rarity.slice(0, 3)}…` : prize.rarity; ctx.fillText(rarity, x + 21, y + 30); ctx.fillStyle = "#302934"; ctx.font = "800 22px 'Noto Sans JP Caption', sans-serif"; const nameLimit = twoColumns ? (prize.stockType === "limited" ? 13 : 16) : (prize.stockType === "limited" ? 32 : 38); const name = prize.name.length > nameLimit ? `${prize.name.slice(0, nameLimit - 1)}…` : prize.name; ctx.fillText(name, x + 88, y + 31); ctx.fillStyle = "#8f3f5c"; ctx.font = "900 21px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(`${prize.probability}%`, x + (twoColumns ? 390 : 900), y + 30); if (prize.stockType === "limited") { ctx.fillStyle = "#65535c"; ctx.font = "800 17px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(`限定${prize.stock ?? 0}`, x + (twoColumns ? 470 : 1010), y + 29); } });
  ctx.fillStyle = "#382e34"; ctx.fillRect(0, 575, 1200, 100); const remaining = Math.max(0, draft.prizes.length - 12); const noticeX = remaining ? 190 : 40; if (remaining) { ctx.fillStyle = "#ffdbe7"; ctx.font = "900 21px 'Noto Sans JP Caption', sans-serif"; ctx.fillText(`ほか${remaining}景品`, 40, 613); } ctx.fillStyle = "#ffffff"; ctx.font = "700 19px 'Noto Sans JP Caption', sans-serif"; drawWrappedText(ctx, draft.noticeText.trim() || "参加条件・景品の受け取り方法をご確認ください。", noticeX, 610, 1160 - noticeX, 25, 2);
  const link = document.createElement("a"); link.download = "ガチャ告知用パネル.png"; link.href = canvas.toDataURL("image/png"); link.click();
}

export function GachaPlanner() {
  const [draft, setDraft] = useState(createDefaultGachaDraft); const [ready, setReady] = useState(false); const [paste, setPaste] = useState(""); const [notice, setNotice] = useState(""); const result = useMemo(() => analyzeGacha(draft), [draft]); const errorCount = result.warnings.filter(warning => warning.severity === "error").length;
  useEffect(() => { queueMicrotask(() => { const saved = decodeGachaDraft(localStorage.getItem(GACHA_STORAGE_KEY) ?? ""); if (saved) setDraft(saved); setReady(true); }); }, []);
  useEffect(() => { if (ready) localStorage.setItem(GACHA_STORAGE_KEY, encodeGachaDraft(draft)); }, [draft, ready]);
  const patch = <K extends keyof GachaDraft>(key: K, value: GachaDraft[K]) => setDraft(current => ({ ...current, [key]: value }));
  const patchPrize = (index: number, value: Partial<GachaPrize>) => setDraft(current => ({ ...current, prizes: current.prizes.map((p, i) => i === index ? { ...p, ...value } : p) }));
  const importTable = () => { const prizes = parsePrizeTable(paste); if (!prizes.length) { setNotice("読み込める景品が見つかりませんでした。"); return; } setDraft(current => ({ ...current, prizes })); setPaste(""); setNotice(`${prizes.length}件の景品を読み込みました。`); };
  return <main className="gacha-shell">
    <header className="gacha-hero"><p className="eyebrow">企画設計専用・実際の抽選はしません</p><h1>ガチャ設定シミュレーター</h1><p>景品と確率を入力するだけで、ポイント・原価・収支・在庫リスクを確認でき、リスナー向けの告知PNGも自動生成できます。</p><div className="gacha-privacy">入力内容はこの端末内だけに保存されます。AI・サーバー送信は使用しません。</div><aside className="access-notice"><b>現在はすべて無料</b><span>現在、すべての機能を無料でご利用いただけます。今後の機能追加やアップデートに伴い、一部の高度な機能を有料オプション（プレミアムプラン等）として提供する場合があります。あらかじめご了承ください。</span></aside></header>
    <section className="gacha-section"><h2><span>1</span> 企画の前提</h2><div className="gacha-form-grid">
      <label>企画名<input value={draft.projectName} onChange={e => patch("projectName", e.target.value)} maxLength={60}/><small className="gacha-field-help">保存する設定やPNGに表示する名前です。</small></label><label>配信者名（任意）<input value={draft.hostName} onChange={e => patch("hostName", e.target.value)} maxLength={40}/><small className="gacha-field-help">PNGに配信者名を載せたい場合に入力します。</small></label>
      <label>抽選方式<select value={draft.mode} onChange={e => patch("mode", e.target.value as GachaDraft["mode"])}><option value="normal">通常（はずれなし）</option><option value="dark">闇ガチャ（はずれあり）</option></select><small className="gacha-field-help">通常は合計100%。闇ガチャは不足分がはずれ率になります。</small></label><label>ガチャ1回あたりのポイント<input type="number" min="0" inputMode="numeric" value={draft.pointsPerDraw} onChange={e => patch("pointsPerDraw", numeric(e.target.value))}/><small className="gacha-field-help">収支試算では1P＝1円として計算します。</small></label>
      <label>想定ガチャ回数<input type="number" min="1" max="10000" inputMode="numeric" value={draft.plannedDraws} onChange={e => patch("plannedDraws", numeric(e.target.value))}/><small className="gacha-field-help">企画全体でガチャが回されると予想する回数です。</small></label><label>固定費（円）<input type="number" min="0" inputMode="numeric" value={draft.fixedCost} onChange={e => patch("fixedCost", numeric(e.target.value))}/><small className="gacha-field-help">イラスト代など、ガチャ回数に関係なく発生する費用です。</small></label>
      <label>比較するレアリティ<input value={draft.targetRarity} onChange={e => patch("targetRarity", e.target.value)} maxLength={12}/><small className="gacha-field-help">入手確率を詳しく確認したいレアリティを指定します。</small></label>
      <label className="gacha-toggle"><input type="checkbox" checked={draft.bundleEnabled} onChange={e => patch("bundleEnabled", e.target.checked)}/><span>まとめ引きを設定する</span><small className="gacha-field-help">複数回分をまとめたポイント設定がある場合に使います。</small></label>
      {draft.bundleEnabled && <><label>まとめ引きのガチャ回数<input type="number" min="2" max="1000" inputMode="numeric" value={draft.bundleDraws} onChange={e => patch("bundleDraws", numeric(e.target.value))}/><small className="gacha-field-help">まとめ引き1セットに含まれるガチャ回数を入力します。</small></label><label>まとめ引きの必要ポイント<input type="number" min="0" inputMode="numeric" value={draft.bundlePoints} onChange={e => patch("bundlePoints", numeric(e.target.value))}/><small className="gacha-field-help">まとめ引き1セットに必要なポイントを入力します。</small></label></>}
    </div></section>
    <section className="gacha-section"><div className="gacha-section-title"><h2><span>2</span> 景品と確率</h2><div className="gacha-probability-summary"><strong className={result.probabilityTotal > 100.01 || (draft.mode === "normal" && Math.abs(result.probabilityTotal - 100) > .01) ? "is-error" : "is-ok"}>景品合計 {result.probabilityTotal.toFixed(2)}%</strong>{draft.mode === "dark" && <strong>はずれ {result.missProbability.toFixed(2)}%</strong>}</div></div><p className="gacha-help">デジタルグッズは「在庫制限なし」、物理・数量限定景品は「在庫制限あり」を選びます。最大{MAX_GACHA_PRIZES}件です。</p>
      <div className="gacha-prize-list">{draft.prizes.map((p, i) => <article className="gacha-prize" key={p.id}><div className="gacha-prize-head"><strong>景品 {i + 1}</strong><button type="button" disabled={draft.prizes.length === 1} onClick={() => patch("prizes", draft.prizes.filter((_, index) => index !== i))}>削除</button></div><div className="gacha-prize-grid"><label>レア<input value={p.rarity} maxLength={12} onChange={e => patchPrize(i, { rarity: e.target.value })}/></label><label className="gacha-name">景品名<input value={p.name} maxLength={60} onChange={e => patchPrize(i, { name: e.target.value })}/></label><label>確率（%）<input type="number" min="0" max="100" step="0.01" inputMode="decimal" value={p.probability} onChange={e => patchPrize(i, { probability: numeric(e.target.value) })}/></label><label>原価（円）<input type="number" min="0" inputMode="numeric" value={p.cost} onChange={e => patchPrize(i, { cost: numeric(e.target.value) })}/></label><label>在庫の扱い<select value={p.stockType} onChange={e => patchPrize(i, { stockType: e.target.value as GachaPrize["stockType"], stock: e.target.value === "unlimited" ? null : p.stock ?? 0 })}><option value="unlimited">制限なし（デジタル）</option><option value="limited">制限あり</option></select></label>{p.stockType === "limited" && <label>在庫数<input type="number" min="0" inputMode="numeric" value={p.stock ?? 0} onChange={e => patchPrize(i, { stock: numeric(e.target.value) })}/></label>}</div></article>)}</div>
      <button className="button secondary" type="button" disabled={draft.prizes.length >= MAX_GACHA_PRIZES} onClick={() => patch("prizes", [...draft.prizes, { id: crypto.randomUUID(), rarity: "", name: "", probability: 0, cost: 0, stockType: "unlimited", stock: null }])}>＋ 景品を追加</button>
      <details className="gacha-import" open><summary>景品を一括登録（CSV・表から読み込む）</summary><p>CSVの内容、またはExcel・Googleスプレッドシートの表を貼り付けてください。</p><ul><li>対応形式：カンマ区切り／タブ区切り</li><li>列の順番：レアリティ、景品名、確率、原価、在庫</li><li>在庫を空欄にすると「在庫無制限」になります</li><li>読み込むと現在の景品は置き換わります</li></ul><textarea aria-label="CSVまたは表の内容" value={paste} onChange={e => setPaste(e.target.value)} rows={5} placeholder={'S,特賞,2,1000,2\nN,参加賞,98,0,'}/><div className="gacha-import-actions"><button type="button" className="button secondary" onClick={importTable}>貼り付けた内容を読み込む</button><a className="button secondary" href="/api/gacha-template">一括登録用CSVテンプレートをダウンロード</a></div></details>{notice && <p className="gacha-notice" role="status">{notice}</p>}
    </section>
    <section className={`gacha-section gacha-results${errorCount ? " has-errors" : ""}`}><h2><span>3</span> 設計チェック</h2>{errorCount > 0 && <div className="gacha-error-banner" role="alert"><strong>⚠ 設定に要修正があります</strong><span>{errorCount}件のエラーを確認してください。このまま告知・実施しないでください。</span></div>}<p className="gacha-conversion-note">収支試算では1P＝1円として計算します。実際の受取額を保証するものではありません。</p><div className="gacha-metrics"><div><small>想定獲得ポイント</small><strong>{formatPoints(result.totalPoints)}</strong></div><div><small>単発のみの場合</small><strong>{formatPoints(result.singleTotalPoints)}</strong></div>{draft.bundleEnabled && <div><small>まとめ引きによる差</small><strong>{formatPoints(result.bundleSavingPoints)}</strong></div>}<div><small>ガチャ1回あたり実質</small><strong>{formatPoints(result.effectivePointsPerDraw)}</strong></div><div><small>期待原価／回</small><strong>{formatYen(result.expectedCostPerDraw)}</strong></div><div><small>想定総原価</small><strong>{formatYen(result.expectedTotalCost)}</strong></div><div><small>収支見込み</small><strong className={result.expectedMargin < 0 ? "is-error" : "is-ok"}>{formatYen(result.expectedMargin)}</strong></div><div><small>損益分岐</small><strong>{result.breakEvenDraws === null ? "算出不可" : `ガチャ${result.breakEvenDraws}回`}</strong></div><div><small>{draft.mode === "dark" ? "はずれ率" : `${draft.targetRarity}が1回以上出る確率`}</small><strong>{draft.mode === "dark" ? `${result.missProbability.toFixed(2)}%` : formatPercent(result.targetProbabilityAtPlan)}</strong></div></div>
      {draft.bundleEnabled && <p className="gacha-bundle-result">想定ガチャ{draft.plannedDraws}回を、{draft.bundleDraws}連×{result.bundleCount}回＋単発{result.remainingSingleDraws}回として計算しています。</p>}
      <div className="gacha-warnings" aria-label="設定チェック" aria-live="polite">{result.warnings.map(w => <p className={`gacha-warning ${w.severity}`} role={w.severity === "error" ? "alert" : undefined} key={w.code}><b>{w.severity === "error" ? "⚠ 要修正" : w.severity === "warning" ? "要確認" : "情報"}</b><span>{w.message}</span></p>)}</div>
      <div className="gacha-mode-note"><strong>{modeLabels[draft.mode]}</strong><span>{draft.mode === "normal" ? "設定した景品のいずれかが必ず当たる方式です。排出率合計を100%にします。" : `景品が当たらない枠を含む方式です。現在のはずれ率は${result.missProbability.toFixed(2)}%です。`}</span></div>
      <div className="gacha-notice-editor"><label>告知PNGに載せる注意事項（任意）<textarea rows={3} maxLength={160} value={draft.noticeText} onChange={e => patch("noticeText", e.target.value)}/><small className="gacha-field-help">参加条件や景品の受け取り方法などを短く入力します。</small></label></div>
      <div className="gacha-actions"><button className="button" type="button" onClick={() => downloadPng(draft)}>設計確認用PNG</button><button className="button" type="button" onClick={() => downloadListenerPng(draft)}>リスナー向け告知PNG</button><button className="button secondary" type="button" onClick={() => { if (confirm("入力内容を初期設定に戻しますか？")) { localStorage.removeItem(GACHA_STORAGE_KEY); setDraft(createDefaultGachaDraft()); } }}>入力をリセット</button></div>
    </section>
    <aside className="gacha-disclaimer"><strong>ご利用前に</strong><p>ポイント売上は1P＝1円換算の参考値です。表示結果は入力値にもとづく理論上の試算で、実際の受取額・利益・排出結果を保証するものではありません。法務・税務上の助言ではありません。実施前に配信・決済・景品提供に使う各サービスの規約と関係法令をご確認ください。</p></aside>
  </main>;
}
