"use client";

import { useEffect, useRef, useState } from "react";
import { decodePlannerState, PLANNER_STORAGE_KEY } from "@/lib/planner-state";
import { EVENT_CATEGORIES, LIVER_PLANNER_STORAGE_KEY, TASK_CATEGORIES, type EventCategory, type LiverEvent, type LiverPlannerState, type LiverTask, type RankCalendarItem, type TaskCategory, addDays, datesBetween, formatDate, labelDate, makeLiverId, rankCalendarItems, readLiverPlannerState } from "@/lib/liver-planner";

type Tab = "home" | "week" | "ten" | "month";
type RankItem = RankCalendarItem;
const today = () => formatDate(new Date());
const download = (content: string, name: string) => { const url = URL.createObjectURL(new Blob([content], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
const timeSort = <T extends { startTime?: string; time?: string; allDay?: boolean }>(a: T, b: T) => Number(Boolean(a.allDay)) - Number(Boolean(b.allDay)) || (a.startTime ?? a.time ?? "99:99").localeCompare(b.startTime ?? b.time ?? "99:99");
const itemTime = (item: LiverEvent | LiverTask | RankItem) => "startTime" in item ? item.startTime ?? (item.allDay ? "98:00" : "99:00") : "time" in item ? item.time ?? "99:00" : "98:30";
const timeOptions = Array.from({ length: 48 }, (_, index) => `${String(Math.floor(index / 2)).padStart(2, "0")}:${index % 2 ? "30" : "00"}`);
const categoryClass = (category: string, kind: "event" | "task") => `category-tag category-${kind} category-${({ "配信": "red", "作業": "orange", "連絡": "yellow", "打合せ": "blue", "交流": "green", "プライベート": "gray", "申込": "blue", "発注": "orange", "問合せ": "yellow", "提出": "red", "その他": "gray" } as Record<string, string>)[category] ?? "gray"}`;
const dueClass = (date?: string) => {
  if (!date) return "";
  const days = Math.round((new Date(`${date}T12:00:00`).getTime() - new Date(`${today()}T12:00:00`).getTime()) / 86400000);
  return days <= 0 ? "due-red" : days <= 3 ? "due-orange" : days <= 5 ? "due-yellow" : days <= 7 ? "due-green" : "due-blue";
};

export function LiverPlanner() {
  const [state, setState] = useState<LiverPlannerState>({ version: 1, events: [], tasks: [] });
  const [rankItems, setRankItems] = useState<RankItem[]>([]);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState<Tab>("home");
  const [selectedDate, setSelectedDate] = useState(today());
  const [filter, setFilter] = useState("全て");
  const [editing, setEditing] = useState<{ kind: "event" | "task"; id?: string }>();
  const [notice, setNotice] = useState<string>();
  const importRef = useRef<HTMLInputElement>(null);
  const currentToday = today();

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setState(readLiverPlannerState(localStorage.getItem(LIVER_PLANNER_STORAGE_KEY)));
    try {
      const planner = decodePlannerState(localStorage.getItem(PLANNER_STORAGE_KEY) ?? "");
      setRankItems(rankCalendarItems(planner));
    } catch { /* rank calendar is optional */ }
    setReady(true);
  }, []);
  useEffect(() => { if (ready) localStorage.setItem(LIVER_PLANNER_STORAGE_KEY, JSON.stringify(state)); }, [ready, state]);

  const eventsFor = (date: string) => state.events.filter((item) => item.date === date).sort(timeSort);
  const rankFor = (date: string) => rankItems.filter((item) => item.date === date);
  const tasksFor = (date: string) => state.tasks.filter((item) => item.scheduledDate === date || item.dueDate === date).sort(timeSort);
  const todayTasks = state.tasks.filter((item) => !item.completed && (item.scheduledDate === currentToday || item.dueDate === currentToday));
  const deadlines = state.tasks.filter((item) => !item.completed && item.dueDate && item.dueDate > currentToday && item.dueDate <= addDays(currentToday, 3)).sort((a, b) => (a.dueDate ?? "").localeCompare(b.dueDate ?? ""));
  const range7 = datesBetween(currentToday, 7), range10 = datesBetween(currentToday, 10);
  const allUpcoming = range10.flatMap((date) => [...eventsFor(date).map((item) => ({ kind: "予定" as const, date, item })), ...rankFor(date).map((item) => ({ kind: "IRIAM" as const, date, item })), ...tasksFor(date).filter((item) => !item.completed).map((item) => ({ kind: "タスク" as const, date, item }))]).sort((a, b) => a.date.localeCompare(b.date) || itemTime(a.item).localeCompare(itemTime(b.item)));
  const shownUpcoming = allUpcoming.filter((row) => filter === "全て" || row.kind === filter || (filter === "カテゴリ" && "category" in row.item));
  const toggleTask = (id: string) => setState((previous) => ({ ...previous, tasks: previous.tasks.map((task) => task.id === id ? { ...task, completed: !task.completed } : task) }));
  const deleteItem = (kind: "event" | "task", id: string) => { if (!confirm("この項目を削除しますか？")) return; setState((previous) => kind === "event" ? { ...previous, events: previous.events.filter((item) => item.id !== id) } : { ...previous, tasks: previous.tasks.filter((item) => item.id !== id) }); };
  const monthStart = new Date(`${selectedDate.slice(0, 7)}-01T12:00:00`);
  const daysInMonth = new Date(monthStart.getFullYear(), monthStart.getMonth() + 1, 0).getDate();
  const calendarDays = Array.from({ length: daysInMonth }, (_, index) => `${selectedDate.slice(0, 7)}-${String(index + 1).padStart(2, "0")}`);

  const exportJson = () => { download(JSON.stringify(state, null, 2), "liver-planner.json"); setNotice("手帳の控えを保存しました。"); };
  const importJson = async (file?: File) => { if (!file) return; try { const saved = readLiverPlannerState(await file.text()); setState(saved); setNotice("保存していた手帳を復元しました。"); } catch { setNotice("保存ファイルを読み込めませんでした。"); } };

  return <section className="liver-planner planner-shell">
    <div className="tool-intro liver-intro"><span className="eyebrow">liver planner</span><h1>ライバー手帳（仮）</h1><p>予定は配信や外出などのスケジュール。タスクは締切や期日のある作業です。</p></div>
    <aside className="planner-persistence-notice liver-storage-note">入力内容はこの端末に自動保存され、サイトには送信されません。</aside>
    <aside className="liver-rank-note"><b>IRIAMランク管理カレンダーと連携</b><span>ランク管理カレンダーに入力した配信予定は、この手帳に自動で表示されます。</span></aside>
    <div className="liver-toolbar"><div className="liver-tabs" aria-label="表示切替">{([ ["home", "ホーム"], ["week", "今週"], ["ten", "直近10日"], ["month", "月" ]] as const).map(([key, label]) => <button type="button" className={tab === key ? "active" : ""} onClick={() => setTab(key)} key={key}>{label}</button>)}</div><div className="liver-actions"><button className="button secondary" type="button" onClick={() => setEditing({ kind: "event" })}>予定を登録<span>配信や外出などのスケジュール</span></button><button className="button" type="button" onClick={() => setEditing({ kind: "task" })}>タスクを登録<span>締切や期日のある作業</span></button></div></div>
    {notice && <p className="planner-persistence-notice" role="status">{notice}</p>}
    {tab === "home" && <div className="liver-sections">
      <PlannerSection title="今日締切"><TaskList tasks={state.tasks.filter((item) => !item.completed && item.dueDate === currentToday)} onToggle={toggleTask} onEdit={(id) => setEditing({ kind: "task", id })} /></PlannerSection>
      <PlannerSection title="今日の予定"><Agenda events={eventsFor(currentToday)} rank={rankFor(currentToday)} onEdit={(id) => setEditing({ kind: "event", id })} onDelete={(id) => deleteItem("event", id)} /></PlannerSection>
      <PlannerSection title="今日のタスク"><TaskList tasks={todayTasks} onToggle={toggleTask} onEdit={(id) => setEditing({ kind: "task", id })} /></PlannerSection>
      <PlannerSection title="締切が近いタスク"><TaskList tasks={deadlines} onToggle={toggleTask} onEdit={(id) => setEditing({ kind: "task", id })} /></PlannerSection>
      <PlannerSection title="今週の予定"><WeekRows dates={range7} eventsFor={eventsFor} rankFor={rankFor} tasksFor={tasksFor} onToggleTask={toggleTask} onEditEvent={(id) => setEditing({ kind: "event", id })} onEditTask={(id) => setEditing({ kind: "task", id })} /></PlannerSection>
    </div>}
    {tab === "week" && <PlannerSection title="今週"><WeekRows dates={range7} eventsFor={eventsFor} rankFor={rankFor} tasksFor={tasksFor} onToggleTask={toggleTask} onEditEvent={(id) => setEditing({ kind: "event", id })} onEditTask={(id) => setEditing({ kind: "task", id })} /></PlannerSection>}
    {tab === "ten" && <PlannerSection title="直近10日"><div className="liver-filter">{["全て", "予定", "タスク", "IRIAM", "カテゴリ"].map((value) => <button type="button" className={filter === value ? "active" : ""} onClick={() => setFilter(value)} key={value}>{value}</button>)}</div><div className="agenda-list">{shownUpcoming.length ? shownUpcoming.map(({ kind, date, item }, index) => <div className="agenda-row" key={`${kind}-${index}`}><b>{labelDate(date)}</b><span>{itemTime(item) === "99:00" ? "" : itemTime(item) === "98:00" ? "終日" : itemTime(item)}</span><div><em className={"category" in item ? categoryClass(item.category, kind === "予定" ? "event" : "task") : "category-tag category-event category-red"}>{"category" in item ? item.category : kind}</em><strong>{item.title}</strong>{item.memo && <small>{item.memo}</small>}</div></div>) : <Empty />}</div></PlannerSection>}
    {tab === "month" && <PlannerSection title={`${selectedDate.slice(0, 7).replace("-", "年")}月`}><div className="month-nav"><button type="button" onClick={() => setSelectedDate(addDays(`${selectedDate.slice(0, 7)}-01`, -1))}>前の月</button><button type="button" onClick={() => setSelectedDate(currentToday)}>今日</button><button type="button" onClick={() => setSelectedDate(addDays(`${selectedDate.slice(0, 7)}-28`, 40))}>次の月</button></div><div className="liver-calendar">{["日", "月", "火", "水", "木", "金", "土"].map((day) => <b key={day}>{day}</b>)}{Array.from({ length: monthStart.getDay() }, (_, i) => <span key={`blank-${i}`} />)}{calendarDays.map((date) => <button type="button" className={selectedDate === date ? "selected" : ""} onClick={() => setSelectedDate(date)} key={date}><b>{Number(date.slice(-2))}</b>{rankFor(date).length + eventsFor(date).length + tasksFor(date).length > 0 && <small>{rankFor(date).length + eventsFor(date).length + tasksFor(date).length}件</small>}</button>)}</div><div className="selected-day"><h3>{labelDate(selectedDate)}</h3><Agenda events={eventsFor(selectedDate)} rank={rankFor(selectedDate)} onEdit={(id) => setEditing({ kind: "event", id })} onDelete={(id) => deleteItem("event", id)} /><TaskList tasks={tasksFor(selectedDate)} onToggle={toggleTask} onEdit={(id) => setEditing({ kind: "task", id })} /></div></PlannerSection>}
    <div className="liver-backup"><span>手帳の引き継ぎ</span><button className="text-button" type="button" onClick={exportJson}>この手帳を保存する</button><button className="text-button" type="button" onClick={() => importRef.current?.click()}>保存した手帳を復元する</button><input ref={importRef} type="file" accept="application/json" hidden onChange={(event) => void importJson(event.target.files?.[0])} /></div>
    {editing?.kind === "event" && <EventEditor item={state.events.find((item) => item.id === editing.id)} defaultDate={selectedDate} onClose={() => setEditing(undefined)} onSave={(item) => { setState((previous) => ({ ...previous, events: editing.id ? previous.events.map((event) => event.id === editing.id ? item : event) : [...previous.events, item] })); setEditing(undefined); }} onDelete={editing.id ? () => { deleteItem("event", editing.id!); setEditing(undefined); } : undefined} />}
    {editing?.kind === "task" && <TaskEditor item={state.tasks.find((item) => item.id === editing.id)} onClose={() => setEditing(undefined)} onSave={(item) => { setState((previous) => ({ ...previous, tasks: editing.id ? previous.tasks.map((task) => task.id === editing.id ? item : task) : [...previous.tasks, item] })); setEditing(undefined); }} onDelete={editing.id ? () => { deleteItem("task", editing.id!); setEditing(undefined); } : undefined} />}
  </section>;
}

function PlannerSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="liver-section"><h2>{title}</h2>{children}</section>; }
function Empty() { return <p className="liver-empty">まだありません。右上のボタンから追加できます。</p>; }
function Agenda({ events, rank, onEdit, onDelete }: { events: LiverEvent[]; rank: RankItem[]; onEdit: (id: string) => void; onDelete: (id: string) => void }) { return <div className="agenda-list">{events.length || rank.length ? <>{events.sort(timeSort).map((item) => <div className="agenda-row" key={item.id}><span>{item.startTime ?? (item.allDay ? "終日" : "")}</span><div><em className={categoryClass(item.category, "event")}>{item.category}</em><strong>{item.title}</strong>{item.memo && <small>{item.memo}</small>}</div><aside><button type="button" onClick={() => onEdit(item.id)}>編集</button><button type="button" onClick={() => onDelete(item.id)}>削除</button></aside></div>)}{rank.map((item) => <div className="agenda-row" key={`${item.date}-${item.title}`}><span></span><div><em className="category-tag category-event category-red">IRIAM</em><strong>{item.title}</strong>{item.memo && <small>{item.memo}</small>}</div></div>)}</> : <Empty />}</div>; }
function TaskList({ tasks, onToggle, onEdit }: { tasks: LiverTask[]; onToggle: (id: string) => void; onEdit: (id: string) => void }) { return <div className="task-list">{tasks.length ? tasks.map((task) => <div className={`task-row ${task.completed ? "done" : ""}`} key={task.id}><input aria-label={`${task.title}を完了`} type="checkbox" checked={task.completed} onChange={() => onToggle(task.id)} /><div><em className={categoryClass(task.category, "task")}>{task.category}</em><strong>{task.title}</strong><small className="task-meta">{task.dueDate && <b className={`task-due ${dueClass(task.dueDate)}`}>締切 {task.dueDate}</b>}{task.memo && <span>{task.memo}</span>}</small></div><button type="button" onClick={() => onEdit(task.id)}>編集</button></div>) : <Empty />}</div>; }
function WeekRows({ dates, eventsFor, rankFor, tasksFor, onToggleTask, onEditEvent, onEditTask }: { dates: string[]; eventsFor: (date: string) => LiverEvent[]; rankFor: (date: string) => RankItem[]; tasksFor: (date: string) => LiverTask[]; onToggleTask: (id: string) => void; onEditEvent: (id: string) => void; onEditTask: (id: string) => void }) { return <div className="week-rows">{dates.map((date) => <div className="week-row" key={date}><h3>{labelDate(date)}</h3><Agenda events={eventsFor(date)} rank={rankFor(date)} onEdit={onEditEvent} onDelete={() => {}} /><TaskList tasks={tasksFor(date)} onToggle={onToggleTask} onEdit={onEditTask} /></div>)}</div>; }

function EditorShell({ title, children, onClose, onDelete, onSave }: { title: string; children: React.ReactNode; onClose: () => void; onDelete?: () => void; onSave: () => void }) { return <div className="liver-modal" role="dialog" aria-modal="true"><form className="liver-editor" onSubmit={(event) => { event.preventDefault(); onSave(); }}><header><h2>{title}</h2><button type="button" onClick={onClose}>閉じる</button></header>{children}<footer>{onDelete && <button className="delete-button" type="button" onClick={onDelete}>削除</button>}<button className="button" type="submit">保存</button></footer></form></div>; }
function EventEditor({ item, defaultDate, onClose, onSave, onDelete }: { item?: LiverEvent; defaultDate: string; onClose: () => void; onSave: (item: LiverEvent) => void; onDelete?: () => void }) { const [value, setValue] = useState<LiverEvent>(item ?? { id: makeLiverId(), title: "", date: defaultDate, allDay: false, category: "配信" }); return <EditorShell title={item ? "予定を編集" : "予定を登録"} onClose={onClose} onDelete={onDelete} onSave={() => onSave(value)}><div className="editor-fields"><label>タイトル<input autoFocus required value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} /></label><label>日付<input type="date" required value={value.date} onChange={(e) => setValue({ ...value, date: e.target.value })} /></label><label className="check-label"><input type="checkbox" checked={value.allDay} onChange={(e) => setValue({ ...value, allDay: e.target.checked })} />終日</label>{!value.allDay && <><p className="time-select-note">時刻は30分刻みで登録できます</p><label>開始時刻<select value={value.startTime ?? ""} onChange={(e) => setValue({ ...value, startTime: e.target.value || undefined })}><option value="">選択しない</option>{timeOptions.map((time) => <option value={time} key={time}>{time}</option>)}</select></label><label>終了時刻<select value={value.endTime ?? ""} onChange={(e) => setValue({ ...value, endTime: e.target.value || undefined })}><option value="">選択しない</option>{timeOptions.map((time) => <option value={time} key={time}>{time}</option>)}</select></label></>}<label>カテゴリ<select value={value.category} onChange={(e) => setValue({ ...value, category: e.target.value as EventCategory })}>{EVENT_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label><label>メモ<textarea value={value.memo ?? ""} onChange={(e) => setValue({ ...value, memo: e.target.value || undefined })} /></label></div></EditorShell>; }
function TaskEditor({ item, onClose, onSave, onDelete }: { item?: LiverTask; onClose: () => void; onSave: (item: LiverTask) => void; onDelete?: () => void }) { const [value, setValue] = useState<LiverTask>(item ?? { id: makeLiverId(), title: "", category: "その他", completed: false }); return <EditorShell title={item ? "タスクを編集" : "タスクを登録"} onClose={onClose} onDelete={onDelete} onSave={() => onSave(value)}><div className="editor-fields"><label>タイトル<input autoFocus required value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} /></label><label>締切日<input type="date" required value={value.dueDate ?? ""} onChange={(e) => setValue({ ...value, dueDate: e.target.value || undefined })} /></label><p className="time-select-note">時刻は30分刻みで登録できます</p><label>締切り時刻<select value={value.time ?? ""} onChange={(e) => setValue({ ...value, time: e.target.value || undefined })}><option value="">選択しない</option>{timeOptions.map((time) => <option value={time} key={time}>{time}</option>)}</select></label><label>カテゴリ<select value={value.category} onChange={(e) => setValue({ ...value, category: e.target.value as TaskCategory })}>{TASK_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label><label>メモ<textarea value={value.memo ?? ""} onChange={(e) => setValue({ ...value, memo: e.target.value || undefined })} /></label></div></EditorShell>; }
